# 1. Cấu hình H2 Database lưu dữ liệu ra một file nằm ngay trong thư mục dự án
spring.datasource.url=jdbc:h2:file:./music_data/MusicAppDB;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Cấu hình JPA (Tự động tạo bảng dựa trên code Java)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. BẬT GIAO DIỆN QUẢN LÝ DATABASE TRÊN TRÌNH DUYỆT (Rất quan trọng)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Cho phép tải file tối đa 50MB (Bạn có thể tăng lên 100MB nếu tải video nặng)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# CẤU HÌNH GỬI EMAIL BẰNG GMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username="your mail"
spring.mail.password="your mail key"
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
