package com.musicapp.services;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Service
public class AudioProcessingService {

    private static final Logger log = LoggerFactory.getLogger(AudioProcessingService.class);
    private static final long MAX_WHISPER_SIZE_BYTES = 24 * 1024 * 1024; // 24MB

    public static class AudioChunk {
        private final File file;
        private final double timeOffsetSeconds;
        private final boolean temporary;

        public AudioChunk(File file, double timeOffsetSeconds, boolean temporary) {
            this.file = file;
            this.timeOffsetSeconds = timeOffsetSeconds;
            this.temporary = temporary;
        }

        public File getFile() { return file; }
        public double getTimeOffsetSeconds() { return timeOffsetSeconds; }
        public boolean isTemporary() { return temporary; }
    }

    public List<AudioChunk> prepareAudioChunks(File audioFile) throws IOException {
        List<AudioChunk> chunks = new ArrayList<>();
        if (audioFile == null || !audioFile.exists()) {
            throw new IllegalArgumentException("Audio file does not exist");
        }

        long size = audioFile.length();
        if (size <= MAX_WHISPER_SIZE_BYTES) {
            log.info("Audio file size {} bytes is under 24MB limit, no chunking needed.", size);
            chunks.add(new AudioChunk(audioFile, 0.0, false));
            return chunks;
        }

        log.info("Audio file size {} bytes exceeds 24MB limit. Attempting to chunk with ffmpeg...", size);
        File tempDir = new File("./music_data/temp/" + UUID.randomUUID());
        if (!tempDir.exists() && !tempDir.mkdirs()) {
            throw new IOException("Failed to create temporary directory for audio chunks");
        }

        String filename = audioFile.getName();
        String ext = "";
        int dotIdx = filename.lastIndexOf('.');
        if (dotIdx >= 0) {
            ext = filename.substring(dotIdx + 1);
        }
        final String finalExt = ext.isEmpty() ? "mp3" : ext;

        String outputPattern = tempDir.getAbsolutePath() + File.separator + "chunk_%03d." + finalExt;

        try {
            ProcessBuilder pb = new ProcessBuilder(
                    "ffmpeg", "-y", "-i", audioFile.getAbsolutePath(),
                    "-f", "segment", "-segment_time", "600", "-c", "copy",
                    outputPattern
            );
            pb.redirectErrorStream(true);
            Process process = pb.start();
            int exitCode = process.waitFor();
            if (exitCode != 0) {
                throw new IOException("ffmpeg exited with code " + exitCode);
            }

            File[] chunkFiles = tempDir.listFiles((dir, name) -> name.startsWith("chunk_") && name.endsWith("." + finalExt));
            if (chunkFiles == null || chunkFiles.length == 0) {
                throw new IOException("No chunks generated by ffmpeg");
            }

            // Sort files by name to ensure correct order
            java.util.Arrays.sort(chunkFiles, (f1, f2) -> f1.getName().compareTo(f2.getName()));

            for (int i = 0; i < chunkFiles.length; i++) {
                double offset = i * 600.0;
                chunks.add(new AudioChunk(chunkFiles[i], offset, true));
                log.info("Generated chunk: {} with offset {} seconds", chunkFiles[i].getName(), offset);
            }

        } catch (Exception e) {
            log.error("Failed to chunk audio file with ffmpeg: {}. Whisper transcription might fail if file is too large.", e.getMessage(), e);
            // Clean up temp dir if any
            cleanUpTempDir(tempDir);
            throw new IOException("Failed to chunk audio file: " + e.getMessage(), e);
        }

        return chunks;
    }

    public void cleanUpChunks(List<AudioChunk> chunks) {
        if (chunks == null) return;
        for (AudioChunk chunk : chunks) {
            if (chunk.isTemporary() && chunk.getFile().exists()) {
                try {
                    Files.delete(chunk.getFile().toPath());
                    log.debug("Deleted temporary chunk file: {}", chunk.getFile().getName());
                } catch (IOException e) {
                    log.warn("Failed to delete temporary chunk file {}: {}", chunk.getFile().getAbsolutePath(), e.getMessage());
                }
            }
        }
    }

    private void cleanUpTempDir(File tempDir) {
        if (tempDir == null || !tempDir.exists()) return;
        File[] files = tempDir.listFiles();
        if (files != null) {
            for (File f : files) {
                f.delete();
            }
        }
        tempDir.delete();
    }
}
